import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from './Header'
import Footer from "./Footer";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

      <html lang="en">

        <body className={inter.className}>
          <SignedOut>

            <div className="bg-green-400 text-white font-semibold m-4 py-3 px-6 w-20 rounded-lg shadow-md hover:bg-green-500 transition duration-300 ease-in-out">
              <SignInButton />
            </div>
          </SignedOut>
          <SignedIn >
            <div className="absolute top-4 left-4">
              <UserButton />
            </div>
            <Header />
          </SignedIn>

          {children}
          <Footer />
        </body>

      </html>
    </ClerkProvider>

  );
}
